# Generated by Django 3.0.7 on 2020-06-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
