# Generated by Django 3.0.7 on 2020-06-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200621_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Employee',
        ),
    ]
