# Generated by Django 3.0.7 on 2020-06-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200621_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='alias',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='last_name',
        ),
    ]
